# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5df1706ac0268da47af978f0e025c6a697fdf3ac7ae765bcd6ffa78ce714d3f9859a65dfb01fd126111a15cf322235bf323fa30d415f3867cdc17fbf04a3f57f

test:
  secret_key_base: 2d98406f2c1f869ce02d8bb12b10330fef0886681f90ef7857a89fa54f1d03810254654a96adf7062e45a586a7b77e641986b72ecfe6bc82e11959fad92b4155

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
